name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: |
          chmod +x ./gradlew
          ./gradlew build --debug build

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker & Push
        run : |
            docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build --platform linux/arm64/v8 -t ${{ secrets.DOCKER_REPO }}/spring-app .  
            docker push ${{ secrets.DOCKER_REPO }}/spring-app

      - name : Docker deploy
        uses : appleboy/ssh-action@master
        with :
          host : ${{ secrets.HOST }}
          username : ${{ secrets.USERNAME }}
          key : ${{ secrets.SSH_PRIVATE_KEY }}
          port : ${{ secrets.SSH_PORT }}
          script: |
            cd app
            sudo rm concal.log
            sudo docker stop $(docker ps -q) && sudo docker rm $(docker ps -a -q) 
            sudo docker image rm ${{ secrets.DOCKER_REPO }}/spring-app
            sudo docker pull ${{ secrets.DOCKER_REPO }}/spring-app
            sudo docker run -p 50000:8080 -d ${{ secrets.DOCKER_REPO }}/spring-app
            sudo docker logs -f spring-app &> concal.log &
            docker image prune -f